export const FETCHING_DATA_CORONA = 'FETCHING_DATA_CORONA';
export const FETCHING_DATA_CORONA_DAILY = 'FETCHING_DATA_CORONA_DAILY';
export const FETCHING_DATA_CORONA_COUNTRIES = 'FETCHING_DATA_CORONA_COUNTRIES';
export const HANDLE_CHANGE_DATE = 'HANDLE_CHANGE_DATE';
